kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefilecustom
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: samplestorage
...
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefilecustom
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefilecustom
  resources:
    requests:
      storage: 5Gi